### ISSUE TITLE
Withdrawals from bsc to stellar are not being processed

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#109]
From the master logs:
```
INFO [06-26|14:00:23.123] Remembering withdraw event for txHash=2c322f…c3a5a1 height=8635075 network=stellar
INFO [06-26|14:19:11.190] Remembering withdraw event for txHash=b67d12…cd4f45 height=8635451 network=stellar
```
No further logs found for the processing of these withdrawals

**Comment by DylanVerstraete** [comment]
going to try to reproduce on testnet once https://github.com/threefoldfoundation/tft/issues/111 is done

**Comment by robvanmieghem** [comment]
Restarted  of the master, after a while it bstarted processing the withdrawals but could not reach the cosigner. Restarted the cosigner and they went through. Closing for now, hope the little bit of extra logging might make us a bit wiser.
