### ISSUE TITLE
Stellar timeout when fetching transactions

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tft#114]
Requests to stellar horizon can timeout on boot

```
INFO [06-30|06:35:56.143] Error getting transactions for stellar account error="horizon error: \"Timeout\" - check horizon.Error.Problem for more information"
```

**Comment by robvanmieghem** [comment]
I don't think it's a boot problem:
[tftbscbridge-54f48cd5d8-6l9vt.log](https://github.com/threefoldfoundation/tft/files/6741958/tftbscbridge-54f48cd5d8-6l9vt.log)

**Comment by robvanmieghem** [comment]
Don't really like the string comparison for the error checking, reopening
