### ISSUE TITLE
Move the binance bridge code to this repo

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#12]
in `bsc/bridges/stellar`

**Comment by robvanmieghem** [comment]
The tft-stellar repo still has the feat/ethereum-stellar-bridge branch

**Comment by robvanmieghem** [comment]
and the imports are not replaced, for example in main.go: `github.com/threefoldfoundation/tft-stellar/eth-bridge/api/bridge`

**Comment by DylanVerstraete** [comment]
> and the imports are not replaced, for example in main.go: `github.com/threefoldfoundation/tft-stellar/eth-bridge/api/bridge`

done

**Comment by DylanVerstraete** [comment]
> The tft-stellar repo still has the feat/ethereum-stellar-bridge branch

removed pr's and braches
