### ISSUE TITLE
Stellar -> BSC bridge transaction did not go through 

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/tft#120]
Hello, 
Bridge transaction: https://stellar.expert/explorer/public/tx/156874681214722048#156874681214722049
Did not arrive to the destination address: https://bscscan.com/address/0x774f72F1570bB09079b0C50BD4870380EEaA9371#tokentxns

**Comment by sabrinasadik** [comment]
@robvanmieghem can you take a look at this please?

**Comment by robvanmieghem** [comment]
This is working again and that transaction has been processed but 
@nbabenko a mint transaction on the contract is not a bep-20 token transaction but a mint method call on the token contract from a multisig contract. The bep-20 spec only specifies transfer methods and such so mint transactions do not show in the bep-20 transactions on bscscan.

**Comment by nbabenko** [comment]
Arrived, thank you
