### ISSUE TITLE
The bridge did not refund a deposit with an invalid memo text

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#129]
version: tftstellarbscbridge:1.0.2

Stellar transaction: 85f9b4288cbab2c22356821b96b262df95a4240a9263f292b6a1b1b825308d24
The memo text of this transaction ("half") is not a valid base64 encoded bsc address but it was ignored and not refunded.

**Comment by DylanVerstraete** [comment]
Blocked on Stellar testnet reset in order to test a solution

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tft/pull/106
