### ISSUE TITLE
Can't withdraw from BSC > Stellar

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/tft#132]
Attempting to bridge TFT from BSC > Stellar does not work, stuck on spinning wheel.

**Comment by Moka414** [comment]
Hello, the bridge is not working and my tokens also did not arrive at the destination address

**Comment by DylanVerstraete** [comment]
Just tried depositing/withdrawing, it went without an issue

**Comment by DylanVerstraete** [comment]
desosittx: https://stellar.expert/explorer/public/tx/168259604429164544#168259604429164546
withdrawtx: https://stellar.expert/explorer/public/tx/168259686033932288#168259686033932289

**Comment by scottyeager** [comment]
The issue seems to be in the withdraw amount. I was attempting to bridge my entire balance, subtracting 1 for the transaction fee. Only when I chose an amount of 2 less than my current TFT balance did the bridge succeed.

Since bridge fee is taken from the bridged amount, seems it should be possible to bridge the entire balance, as populated in the field by default.
