### ISSUE TITLE
The funds have arrived! thanks for good job

### ISSUE THREAD

**Issue by dima777tt** [threefoldfoundation/tft#137]
The funds have arrived! thanks for good job

_Originally posted by @dima777tt in https://github.com/threefoldfoundation/tft/issues/135#issuecomment-1027705151_

NEW transaction: https://stellar.expert/explorer/public/tx/59cebfeaf35c6cb70c09e992284d03099d2e98bbd202c7a39d0b55627f372bf3

**Comment by dima777tt** [comment]
I'm sorry, but the bridge still doesn't work.

**Comment by robvanmieghem** [comment]
It was having a temporary problem getting connections to enough suitable peers.

**Comment by robvanmieghem** [comment]
@dima777tt can this be closed now?

**Comment by dima777tt** [comment]
Good afternoon, again the same problem - the funds did not arrive at the BSC address! Here is the hash: 4134849d9f29141881c17192a782d1a4036fe53f570f4fac3a314adc15b06ee5

**Comment by dima777tt** [comment]
I also see other pending transactions....
