### ISSUE TITLE
TFT Stellar <-> Binance chain bridge

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tft#14]
Currently we are looking to create a bridge from Stellar to Binance.

Things to do:

- [ ] refactor the bridge to work with a multisignature bridge account
   - [x] define specs
   - [x] deploy the bridge in a multi-bridge testnet environment
   - [x] bridge multisig on binance
   - [x] bridge multisig on stellar
   - [x] add bridge validation on withdraw transactions
- [ ] create a website where the user can interact with the TFT Contract on binance chain
   - [x] deploy tft on binance chain: https://testnet.bscscan.com/address/0x770b0AA8b5B4f140cdA2F4d77205ceBe5f3D3C7e
   - [x] deploy tft on binance chain production network
   - [x] create a portal where to user can authorize it's web3 wallet and interact with the bridge contract to send tokens back to a Stellar address

**Comment by sasha-astiadi** [comment]
ready for testing: monday 26 april 2021
release : max. may 3, 2021

**Comment by DylanVerstraete** [comment]
Done
