### ISSUE TITLE
Make bridge more stable or implement protection so tokens get returned back if bridge is down

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/tft#143]
Hello, there were a request from Russain-speaking community that Kristof noted and asked to translate to him:
![image](https://user-images.githubusercontent.com/4426772/154989920-f09dd255-be96-4df6-b406-cd44d0583ee2.png)
he says 
" Dear developers, your bridge to Binance chain is regularly going down and when tokens are sent they just got stuck in the bridge. Please please modify it so it returns tokens back if it does not work since you are putting tokens owner in a bad position, token price is moving and not frozen. Please let's be respectful to each other"
I've informed that this request was passed directly to Kristof. 
Can we do something about it?

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tft/issues/138

**Comment by robvanmieghem** [comment]
The bridge is more stable now and if there are still stability issues, we need to address them.
