### ISSUE TITLE
Specify transfer fee is taken from sent amount

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/tft#147]
Users bridging TFT to BSC are sometimes confused about how the bridge fee is taken. Suggest adjusting the wording to say something like:

`Deposit fee of 50 TFT will be taken from the amount you send`

or

`Please add 50 TFT to the amount you want to transfer to cover deposit fee`

**Comment by robvanmieghem** [comment]
Fixed in the code but this version is not deployed yet
