### ISSUE TITLE
TFT contracts deployment on Polygon (Matic) 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#166]
TODO:

- [x] #167 
- [x] #168
- [ ] Test it
- [ ] Deploy on Production

**Comment by amiraabouhadid** [comment]
Followed tutorial https://wiki.polygon.technology/docs/develop/remix.
Deployed contracts on Mumbai testnet addresses:

storage.sol: 0xf8e81D47203A594245E36C48e151709F0C19fBe8
token_storage.sol: 0xd8b934580fcE35a11B58C6D73aDeE468a2833fa8
owned.sol: 0xD7ACd2a9FD159E69Bb102A1ca21C9a3e3A5F771B
upgradable.sol: 0x7EF2e0048f5bAeDe046f6BF797943daF4ED8CB47
owned_upgradable_token_storage.sol: 0xDA0bab807633f07f013f94DD0E6A4F96F8742B53
tokenV0.sol: 0x9D7f74d0C41E726EC95884E0e97Fa6129e3b5E99
proxy.sol: 0xd8b934580fcE35a11B58C6D73aDeE468a2833fa8

**Comment by robvanmieghem** [comment]
Well done but the goal is not just to make a testnet deployment but to add to the doc so any developer can do so and to test and document it before we make a production deployment.
If the procedures for BSC and Polygon  are equal, extract the doc from BSC, modify it and reference to it from from the BSC and Polygon docs

**Comment by amiraabouhadid** [comment]
Using the deploy token contract address https://github.com/threefoldfoundation/tft/blob/main/bsc/development.md#deploy-the-contract-yourself:~:text=Select%20proxy.sol%20in%20the%20source%20file%20editor%20tab%2C%20change%20this%20with%20your%20deployed%20Token%20contract%20address. throws the following address; 

![Screenshot from 2022-10-26 12-43-29](https://user-images.githubusercontent.com/56790126/198006548-eadf9d4d-59b9-4c9d-a1cf-009069c8b5d3.png)

but using the deployed token_storage.sol address works.

**Comment by robvanmieghem** [comment]
don't get what you mean

**Comment by amiraabouhadid** [comment]
ah my bad was entering the token contract address in the wrong input field

**Comment by amiraabouhadid** [comment]
Regarding multisigs on polygon: https://wiki.polygon.technology/docs/faq/commit-chain-multisigs/
file:///home/amira/Pictures/Screenshots/Screenshot%20from%202022-10-26%2014-04-21.png
![Screenshot from 2022-10-26 14-04-21](https://user-images.githubusercontent.com/56790126/198021753-53a8496d-74b9-4137-a075-b822f83d6314.png)
