### ISSUE TITLE
Document how to add BSC TFT to popular wallets like Metamask

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#19]

**Comment by DylanVerstraete** [comment]
We need a contract address first

**Comment by DylanVerstraete** [comment]
https://user-images.githubusercontent.com/17138347/116229904-4cf43c00-a757-11eb-920e-2d515689f21d.mp4

**Comment by robvanmieghem** [comment]
The address you pasted there end on `be0` while in https://github.com/threefoldfoundation/tft/blob/main/bsc/development.md#tft-on-binance-smart-chain it states that the address is `0x770b0AA8b5B4f140cdA2F4d77205ceBe5f3D3C7e`

**Comment by DylanVerstraete** [comment]
> The address you pasted there end on `be0` while in https://github.com/threefoldfoundation/tft/blob/main/bsc/development.md#tft-on-binance-smart-chain it states that the address is `0x770b0AA8b5B4f140cdA2F4d77205ceBe5f3D3C7e`

updated, was referencing older contract :smile:

**Comment by robvanmieghem** [comment]
It's pretty obvious but it did not work because there was a bug in the proxy contract
