### ISSUE TITLE
Is there a way to show the threefold icon in wallets like metamask for the TFT token?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#20]

**Comment by DylanVerstraete** [comment]
On testnet it is not possible, on mainnet you have to make a request to  BCS Scan team for your token with som extra information.

link to form: https://docs.google.com/forms/d/e/1FAIpQLScIqEkR-QUwdTOavzs3eg2s9mhfLNCd4UoKnqrNQuTEKayqKQ/viewform
