### ISSUE TITLE
Ethereum bridge says "Binance"

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/tft#205]
[This](https://github.com/threefoldfoundation/tft/blob/180b9ca290808d3cbf98a0a25acc27791d101d8b/bsc/bridges/stellar/frontend/components/Deposit.tsx#L38) message, `If you want to swap your Stellar TFT to Binance Chain TFT`, appears on the Ethereum bridge.

**Comment by robvanmieghem** [comment]
f2cb4aff9071dbf18b188e1ffd0d76da372b5016
