### ISSUE TITLE
BSC bridge does not give an error when submitting to a wrong multisig contract

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#23]
I was running a bridge master myself without explicitly setting a mscontract address,making it fall back to the default one . The bridge happily submitted the minttransaction to the multisig contract and did not detect that something was wrong while it's address is not listed as an owner in the default multisig contract.

**Comment by DylanVerstraete** [comment]
It's not possible to submit a transaction to a multisig contract if you are not one of the X owners of that contract.

I reproduced with an account that is not member of the multisig contract and got following stacktrace:

```
INFO [04-29|15:29:18.219] Sumbitting transaction to multisig contract 
WARN [04-29|15:29:18.252] Served eth_sendRawTransaction            reqid=12 t=432.955µs err="insufficient funds for gas * price + value" X-Forwarded-For=nil
ERROR[04-29|15:29:18.252] Error occured while minting: insufficient funds for gas * price + value 
```

**Comment by robvanmieghem** [comment]
I had that error when the account was unfunded with BNB, when the bridge account was funded with BNB, it silently continued

**Comment by DylanVerstraete** [comment]
You are right, but even then the transaction fails on the multisig contract. I just reproduced:

https://testnet.bscscan.com/tx/0xf604f8a13264aa443b71a11841a06a74a4a567744f3a5b8479c9045cc6745795

**Comment by robvanmieghem** [comment]
I know but decent error logginng is important

**Comment by DylanVerstraete** [comment]
Found a potential fix for it, before executing the transaction on the multisig contract I can fetch the owners and check if the bridge address is in that list of owners. If not I return an error and the transaction will not be submitted.

**Comment by robvanmieghem** [comment]
Can't you log the returned transaction id so we can debug in case of weirdness?

**Comment by DylanVerstraete** [comment]
We can yes

**Comment by DylanVerstraete** [comment]
currently implemented this errors logging:

```
INFO [04-29|18:05:44.920] Minting transaction for f2f8370fdc4921562ad4d6daad52ce1ac5d8ce3f 
ERROR[04-29|18:05:45.803] Bridge is not owner of the multisig contract
```
