### ISSUE TITLE
It is not documented how to generate the go bindings for the contracts in the BSC bridge

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#24]
`contract/token.go` and `mscontract/multisig.go` are autogenerated but the docs are missing the command to do so.
Better yet, add a `generate.go` with the commands in there so we can regenerate with `go generate`

**Comment by DylanVerstraete** [comment]
Added in: https://github.com/threefoldfoundation/tft/commit/96f0f957ba84577752ea05bfcbafbb3be3fda723

**Comment by robvanmieghem** [comment]
@DylanVerstraete can you add it in a generate.go file to be more in line with how these things are handled in go?

**Comment by DylanVerstraete** [comment]
added in: 4d0565177852bd8f790e5fa37804522c94bd2e99
