### ISSUE TITLE
Create service for activating a stellar account on behalf of the user

### ISSUE THREAD

**Issue by brandonpille** [threefoldfoundation/tft#240]
It is currently possible to activate a stellar account using [this](https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/activation_service) activation service. Although it works like a charm this activation service sponsors the 1 XLM needed to activate the account. In the [web3 proxy](https://github.com/threefoldtech/web3_proxy) we have the need to create an account on behalf of the user. But this is mostly required for transferring ethereum to tfchain. So instead of using [this](https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/activation_service) activation service we could create a new one that will activate the account given that the user provides a stellar address and transfers some ethereum (enought to pay the 1 XLM to activate the account) to this new service.

**Comment by robvanmieghem** [comment]
The minimum amount of XLM is 1.5 ( base reserve + trustline to TFT), will take 2

**Comment by DylanVerstraete** [comment]
Ethereum gas prices for smart contract are pretty high so I'm not sure adding another $10+ cost to the user is the right approach here. It also requires another service to be run by Threefold and creates a central point of failure. If this service is down than the flow on the web3proxy would break, which is already the case in the current setup.

**Comment by DylanVerstraete** [comment]
I'd rather see this as a part of the ethereum bridge. Where if the user withdraws to a stellar address that does not exist, the bridge activates it and takes some TFT from the withdrawn amount as a fee for it.

**Comment by robvanmieghem** [comment]
What I would prefer most is skipping the Stellar step for the user by extending the Etherum bridge to withdraw directly to tfchain ( under the hood, the vaulted funds would be transferred from the Etherum to the tfchain vault though)

**Comment by DylanVerstraete** [comment]
> What I would prefer most is skipping the Stellar step for the user by extending the Etherum bridge to withdraw directly to tfchain ( under the hood, the vaulted funds would be transferred from the Etherum to the tfchain vault though)

This is also an option worth exploring

**Comment by brandonpille** [comment]
So how do we proceed?

**Comment by DylanVerstraete** [comment]
It seems @robvanmieghem already deployed the implemented service https://github.com/threefoldfoundation/tft/pull/241/commits/d67e5335d7c9f4f78e1120a1d162eaab5aca4b7b so I guess a followup issue will be created ...

**Comment by robvanmieghem** [comment]
Adding Ethereum to tfchain to the Ethereum bridge will mainly save the user gas in this use case ( once per user if there is no Stellar account yet) but will take quite some development effort.

**Comment by robvanmieghem** [comment]
> > What I would prefer most is skipping the Stellar step for the user by extending the Etherum bridge to withdraw directly to tfchain ( under the hood, the vaulted funds would be transferred from the Etherum to the tfchain vault though)
> 
> This is also an option worth exploring

#242
