### ISSUE TITLE
BSC tokenv1 containers

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#255]

**Comment by xmonader** [comment]
While indeed you will be executing this feature @robvanmieghem , I've no clue what this is about, Can you please add more information to the issue

**Comment by robvanmieghem** [comment]
This is part of the v1.5.0 project and milestone. These both have the description "BSC Better Multisig". 
There are two token implementations in the solidity folder: tokenv0( original/current bsc TFT)  and tokenv1 with tokenv1 being an improved multisig implementation which is used by the Ethereum implementation.
In order to support replacing v0 with v1 for TFT on BSC, the bridgecontainers for BSC need to use the bridgeimplementation that supports tokenv1.

**Comment by robvanmieghem** [comment]
The stellar-evm bridge container can simply be reused and the frontend abi does not need modifivation as the withdraw function in the contract has the same signature.
