### ISSUE TITLE
Mint 50 TF ( Fee) less on the bsc side than sent to the bridge

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#31]
Even if it does not transfer it to the feewallet yet, it already works as expected and the transfers can be done later, If that fee is implemented later, we can end up with less TFT in the vault than minted on the bsc side if not carefull. It's better to already substract this amount now.

**Comment by robvanmieghem** [comment]
That's exactly the reason  why I said it's better to implement the substraction of the fee already without everything else of the fees already implemented.

**Comment by robvanmieghem** [comment]
f3f5a7ba5ce016cc1558e6108b94c722a0d06de9

**Comment by DylanVerstraete** [comment]
But what if a user send less than 50 TFT? He just loses it?

**Comment by robvanmieghem** [comment]
I should be refunded then: #35
