### ISSUE TITLE
Deposit/Withdrawal portal

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#43]
TODO:

- [x] publish helm chart in the threefoldfoundation helm repo
- [x] Deploy to staging to test
- [x] Deploy to hagrid

**Comment by DylanVerstraete** [comment]
Can close right? @robvanmieghem

**Comment by robvanmieghem** [comment]
@DylanVerstraete not yet, I want to review the helm chart, and it needs to be deployed on hagrid
