### ISSUE TITLE
Submit information to BSC scan

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tft#75]
Submit information about our token to BSC scan so we can have an icon and some social links

**Comment by robvanmieghem** [comment]
@DylanVerstraete Can't this be closed?

**Comment by DylanVerstraete** [comment]
Information is submitted but not confirmed yet it seems, let's wait until the token tracker page is up to date before we close this.

**Comment by nbabenko** [comment]
Hello Dylan, can you please ping them again if they can update our infomration?

**Comment by DylanVerstraete** [comment]
I contacted bscscan team again, let's hope they update it this week

**Comment by DylanVerstraete** [comment]
Token information is updated! :clinking_glasses:

**Comment by nbabenko** [comment]
Hey @DylanVerstraete , looks like outdated reddit account was submitted there. Here is the correct one: https://www.reddit.com/r/threefold/

**Comment by DylanVerstraete** [comment]
@nbabenko okay I will email them

**Comment by DylanVerstraete** [comment]
@nbabenko information is updated! Redit link is now correct :-)

**Comment by nbabenko** [comment]
cool thank you!
