### ISSUE TITLE
If a withdrawal tx fails , it is never picked up again

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tft#87]
if it fails to get enough signatures for example, it is never picked up again.

**Comment by robvanmieghem** [comment]
@DylanVerstraete Is the BSC blockheight only updated to the node persistency after a successful withdrawal, like the stellarcursor for a deposit?

**Comment by DylanVerstraete** [comment]
@robvanmieghem blockheight is updated every block

**Comment by DylanVerstraete** [comment]
We now only save blockheight when a withdrawal was succeeded, when you now shut down the bridge while there is a failing withdrawal and restart it, it will start retrying the withdrawal. Good catch

https://github.com/threefoldfoundation/tft/commit/d592aee85c56b24a7e5eaaac44f7eeeda7444188
