### ISSUE TITLE
Upload token image to trustwallet image repo

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tft#93]
https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets

**Comment by DylanVerstraete** [comment]
![Screenshot from 2021-05-31 14-26-05](https://user-images.githubusercontent.com/17138347/120193297-891a3100-c21c-11eb-890a-d24701df6523.png)


Wont be able to upload our token asset image because they require atleast 2500 holders, we only have less than 100 at current time of writing

**Comment by nbabenko** [comment]
Hey Dylan, can we argue with them and appeal that we have more than 2500 holders on the main chain? 
https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1?filter=asset-holders

Can we request a call with them?

**Comment by nbabenko** [comment]
Any luck with attempt to submit our token to https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets

btw here is the good example of the format with the links: https://github.com/trustwallet/assets/blob/master/blockchains/smartchain/assets/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82/info.json

**Comment by DylanVerstraete** [comment]
done: https://github.com/trustwallet/assets/pull/12129

**Comment by nbabenko** [comment]
they declined it for now
